import { Project } from '../types/Project'

export const PROJECTS: Project[] = [
   {
      company: `Cardlytics`,
      link: 'https://www.cardlytics.com',
      image: '/projects/cardlytics.jpeg',
      badges: [
         'MUI',
         'React',
         'Vue',
         'SQL',
         'NoSQL',
         'Node',
         'Kafka',
         'JavaScript',
         'TypeScript',
         'AWS',
         'EC2',
         'S3',
         'Serverless',
         'Lambda',
      ],
      title: `Cardlytics (CDLX - NASDAQ)`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Purchase Intelligence helps marketers identify opportunity, reach real people with relevant ads, then precisely measure the results. `,
   },

   {
      company: `Z-Tech`,
      link: 'https://www.linkedin.com/company/z-tech-',
      image: '/projects/ab_inbev.jpeg',
      badges: [
         'UI/UX',
         'React',
         'React Native',
         'React Query',
         'React Context',
         'React Hooks',
         'Nest.js',
         'Node.js',
         'Azure',
         'tRPC',
         'gRPC',
         'CI/CD',
      ],
      title: `Z-Tech (Anheuser-Busch Inbev)`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Z-Tech is an innovation group part of Anheuser-Busch Inbev which mission is to empower small and medium-size businesses to change the world through technology.`,
   },

   {
      company: `University of Miami`,
      link: 'https://www.welcome.miami.edu',
      image: '/projects/university_of_miami.jpg',
      badges: [
         'Android',
         'IOS',
         'WebRTC',
         'Video/Audio',
         'SMS/MMS',
         'React.js',
         'Next.js',
         'Nest.js',
         'Node.js',
         'MUI',
         'Tailwind',
         'API',
         'RESTful',
         'GraphQL',
         'Security',
         'Figma',
         'MongoDB',
         'DynamoDB',
      ],
      title: `University of Miami (Health System)`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Medicine research project (NDA)`,
   },

   {
      company: `Tier1 Financial Solutions`,
      link: 'https://tier1fin.com',
      image: '/projects/tier1fin.jpeg',
      badges: [
         'React',
         'Redux',
         'Hooks',
         'Context',
         'MySQL',
         'PostgreSQL',
         'Node.js',
         'Nest.js',
         'Figma',
         'ORM',
         'CRUD',
      ],
      title: `Tier1 (Financial Solutions)`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Global leader in CRM software for capital markets & investment banking.`,
   },

   {
      company: `Social News Desk`,
      link: 'https://www.socialnewsdesk.com/',
      image: '/projects/socialnewsdesk.jpg',
      badges: [
         'SEO',
         'React',
         'React Native',
         'React Hooks',
         'React Context',
         'Figma',
         'Responsive/Adaptive',
         'UI/UX',
         'JavaScript',
         'TypeScript',
      ],
      title: `Social News Desk`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Social media management tools for today’s critical communicators`,
   },

   {
      company: `Cheap Hotels Hub`,
      link: 'https://cheaphotelshub.com',
      image: '/projects/cheaphotelshub.png',
      badges: [
         'CTO',
         'Technical Leadership',
         'Marketing',
         'Team Leadership',
         'AI',
      ],
      title: `Cheap Hotels Hub`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `AI-powered hotel reservation platform using cutting-edge technology to deliver personalized, real-time hotel recommendations and bookings.`,
   },

   {
      company: `Live Art`,
      link: 'https://liveart.io',
      image: '/projects/liveart.png',
      badges: [
         'UI kit',
         'API kit',
         'WEB2/WEB3',
         'Token',
         'Contract',
         'Payment',
         'Storybook',
         'ERC-721',
         'ERC-1155',
         'NTF',
      ],
      title: `Live Art`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `The World’s #1 ArtFi Ecosystem. LiveArt brings the $2-trillion-dollar art asset class to global crypto audiences.`,
   },

   {
      company: `Pontem Network`,
      link: 'https://pontem.network',
      image: '/projects/pontem.png',
      badges: [
         'WEB3',
         'Wallet',
         'Explorer',
         'React.js',
         'Next.js',
         'Nuxt.js',
         'Vue.js',
         'Swap',
         'Liquidity',
      ],
      title: `Pontem Network`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Pontem is the multichain product studio behind Lumio — the L2 for every VM on every chain. Build once, deploy everywhere with Lumio.`,
   },

   {
      company: `Super Studios`,
      link: 'https://www.superstudios.io',
      image: '/projects/super_studios.jpeg',
      badges: [
         'WEB3',
         'Nuxt.js',
         'Vue.js',
         'Crypto',
         'Token',
         'SEO',
         'Marketing',
         'Optimization',
         'Performance',
         'UI/UX',
         '$SUPER',
      ],
      title: `Super Studios`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Build decentralized Web3 products to accelerate the world's adoption of crypto technology.`,
   },

   {
      company: `Super Verse`,
      link: 'https://superverse.co',
      image: '/projects/super_verse.png',
      badges: [
         'WEB3',
         'Blockchain',
         'Crypto',
         'Token',
         'Vite',
         'Cloudflare',
         'Pipelines',
         'Docker',
         'WebGL',
      ],
      title: `Super Verse`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `The decentralized autonomous organization that powers the SUPER ecosystem.`,
   },

   {
      company: `Impostors`,
      link: 'https://impostors.gg',
      image: '/projects/impostors.png',
      badges: [
         'WEB3',
         'Animation',
         '2D/3D',
         'Nuxt.js',
         'Vue.js',
         'Crypto',
         'NFT',
         'Game',
         'Online',
      ],
      title: `Impostors`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `A Free-to-Play Social Deduction Game Riddled with Intrigue, Excitement, and a Dash of Mystery`,
   },

   {
      company: `DFinance`,
      link: 'https://dfinance.co',
      image: '/projects/dfinance.png',
      badges: [
         'WEB3',
         'Nuxt.js',
         'Vue.js',
         'React.js',
         'Next.js',
         'Tendermint',
         'Cosmos',
         'Move',
      ],
      title: `DFinance`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Dfinance enables you to create and trade your own blockchain-based financial instruments with natural language tools.`,
   },

   {
      company: `PLR`,
      link: 'https://www.plr.me',
      image: '/projects/plr.png',
      badges: [
         'PHP',
         'Laravel',
         'Python',
         'Django',
         'Parsers',
         'Scrappers',
         'HTMl5',
         'CSS3',
         'Canvas 2D/3D',
         'WebGL',
      ],
      title: `Private Label Rights (PLR) Content for Coaches`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Quality private label content for health & life coaches. 100% written by industry experts in US/CAN.`,
   },

   {
      company: `GigaMart`,
      link: 'https://gigamart.com',
      image: '/projects/gigamart.jpg',
      badges: [
         'Web3.js',
         'Ethers.js',
         'NFT',
         'Vue.js',
         'Nuxt.js',
         'Options API',
         'Composition API',
         'JavaScript',
         'TypeScript',
         'Buy/Sell',
         'Crypto',
         'Payment API',
         'Trade API',
         'AI',
      ],
      title: `GigaMart`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Web3 marketplace for NFTs and crypto collectibles. Browse, create, buy, sell, and auction NFTs.`,
   },

   {
      company: `Cryplex`,
      link: 'https://cryplex.io',
      image: '/projects/cryplex.png',
      badges: [
         'Web3.js',
         'Ethers.js',
         'Chart.js',
         'D3.js',
         'Vercel',
         'React',
         'Next',
         'SSR',
         'CSR',
         'SSG',
         'SPA',
         'AI',
         'Tailwind',
         'Radix UI',
         'Headless UI',
         'Parsing',
         'Grabbing',
         'Big Data',
      ],
      title: `Cryplex`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Discover, Review, and Rate Top Crypto Projects from all Ecosystems`,
   },

   // {
   //    company: ``,
   //    link: '',
   //    badges: [''],
   //    title: ``,
   //    logo: undefined,
   //    start: undefined,
   //    end: undefined,
   //    description: ``,
   // },
]
