import { Project } from '../types/Project'

export const PROJECTS: Project[] = [
   // 0 - 15
   {
      company: `Cardlytics`,
      link: 'https://www.cardlytics.com',
      image: '/projects/cardlytics.jpeg',
      badges: [
         'MUI',
         'React',
         'Vue',
         'SQL',
         'NoSQL',
         'Node',
         'Kafka',
         'JavaScript',
         'TypeScript',
         'AWS',
         'EC2',
         'S3',
         'Serverless',
         'Lambda',
      ],
      title: `Cardlytics (CDLX - NASDAQ)`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Purchase Intelligence helps marketers identify opportunity, reach real people with relevant ads, then precisely measure the results. `,
   },

   {
      company: `Z-Tech`,
      link: 'https://www.linkedin.com/company/z-tech-',
      image: '/projects/ab_inbev.jpeg',
      badges: [
         'UI/UX',
         'React',
         'React Native',
         'React Query',
         'React Context',
         'React Hooks',
         'Nest.js',
         'Node.js',
         'Azure',
         'tRPC',
         'gRPC',
         'CI/CD',
      ],
      title: `Z-Tech (Anheuser-Busch Inbev)`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Z-Tech is an innovation group part of Anheuser-Busch Inbev which mission is to empower small and medium-size businesses to change the world through technology.`,
   },

   {
      company: `University of Miami`,
      link: 'https://www.welcome.miami.edu',
      image: '/projects/university_of_miami.jpg',
      badges: [
         'Android',
         'IOS',
         'WebRTC',
         'Video/Audio',
         'SMS/MMS',
         'React.js',
         'Next.js',
         'Nest.js',
         'Node.js',
         'MUI',
         'Tailwind',
         'API',
         'RESTful',
         'GraphQL',
         'Security',
         'Figma',
         'MongoDB',
         'DynamoDB',
      ],
      title: `University of Miami (Health System)`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Medicine research project (NDA)`,
   },

   {
      company: `Tier1 Financial Solutions`,
      link: 'https://tier1fin.com',
      image: '/projects/tier1fin.jpeg',
      badges: [
         'React',
         'Redux',
         'Hooks',
         'Context',
         'MySQL',
         'PostgreSQL',
         'Node.js',
         'Nest.js',
         'Figma',
         'ORM',
         'CRUD',
      ],
      title: `Tier1 (Financial Solutions)`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Global leader in CRM software for capital markets & investment banking.`,
   },

   {
      company: `Social News Desk`,
      link: 'https://www.socialnewsdesk.com/',
      image: '/projects/socialnewsdesk.jpg',
      badges: [
         'SEO',
         'React',
         'React Native',
         'React Hooks',
         'React Context',
         'Figma',
         'Responsive/Adaptive',
         'UI/UX',
         'JavaScript',
         'TypeScript',
      ],
      title: `Social News Desk`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Social media management tools for today’s critical communicators`,
   },

   {
      company: `Cheap Hotels Hub`,
      link: 'https://cheaphotelshub.com',
      image: '/projects/cheaphotelshub.png',
      badges: [
         'CTO',
         'Technical Leadership',
         'Marketing',
         'Team Leadership',
         'AI',
      ],
      title: `Cheap Hotels Hub`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `AI-powered hotel reservation platform using cutting-edge technology to deliver personalized, real-time hotel recommendations and bookings.`,
   },

   {
      company: `Live Art`,
      link: 'https://liveart.io',
      image: '/projects/liveart.png',
      badges: [
         'UI kit',
         'API kit',
         'WEB2/WEB3',
         'Token',
         'Contract',
         'Payment',
         'Storybook',
         'ERC-721',
         'ERC-1155',
         'NTF',
      ],
      title: `Live Art`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `The World’s #1 ArtFi Ecosystem. LiveArt brings the $2-trillion-dollar art asset class to global crypto audiences.`,
   },

   {
      company: `Pontem Network`,
      link: 'https://pontem.network',
      image: '/projects/pontem.png',
      badges: [
         'WEB3',
         'Wallet',
         'Explorer',
         'React.js',
         'Next.js',
         'Nuxt.js',
         'Vue.js',
         'Swap',
         'Liquidity',
      ],
      title: `Pontem Network`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Pontem is the multichain product studio behind Lumio — the L2 for every VM on every chain. Build once, deploy everywhere with Lumio.`,
   },

   {
      company: `Super Studios`,
      link: 'https://www.superstudios.io',
      image: '/projects/super_studios.jpeg',
      badges: [
         'WEB3',
         'Nuxt.js',
         'Vue.js',
         'Crypto',
         'Token',
         'SEO',
         'Marketing',
         'Optimization',
         'Performance',
         'UI/UX',
         '$SUPER',
      ],
      title: `Super Studios`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Build decentralized Web3 products to accelerate the world's adoption of crypto technology.`,
   },

   {
      company: `Super Verse`,
      link: 'https://superverse.co',
      image: '/projects/super_verse.png',
      badges: [
         'WEB3',
         'Blockchain',
         'Crypto',
         'Token',
         'Vite',
         'Cloudflare',
         'Pipelines',
         'Docker',
         'WebGL',
      ],
      title: `Super Verse`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `The decentralized autonomous organization that powers the SUPER ecosystem.`,
   },

   {
      company: `Impostors`,
      link: 'https://impostors.gg',
      image: '/projects/impostors.png',
      badges: [
         'WEB3',
         'Animation',
         '2D/3D',
         'Nuxt.js',
         'Vue.js',
         'Crypto',
         'NFT',
         'Game',
         'Online',
      ],
      title: `Impostors`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `A Free-to-Play Social Deduction Game Riddled with Intrigue, Excitement, and a Dash of Mystery`,
   },

   {
      company: `DFinance`,
      link: 'https://dfinance.co',
      image: '/projects/dfinance.png',
      badges: [
         'WEB3',
         'Nuxt.js',
         'Vue.js',
         'React.js',
         'Next.js',
         'Tendermint',
         'Cosmos',
         'Move',
      ],
      title: `DFinance`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Dfinance enables you to create and trade your own blockchain-based financial instruments with natural language tools.`,
   },

   {
      company: `PLR`,
      link: 'https://www.plr.me',
      image: '/projects/plr.png',
      badges: [
         'PHP',
         'Laravel',
         'Python',
         'Django',
         'Parsers',
         'Scrappers',
         'HTMl5',
         'CSS3',
         'Canvas 2D/3D',
         'WebGL',
      ],
      title: `Private Label Rights (PLR) Content for Coaches`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Quality private label content for health & life coaches. 100% written by industry experts in US/CAN.`,
   },

   {
      company: `GigaMart`,
      link: 'https://gigamart.com',
      image: '/projects/gigamart.jpg',
      badges: [
         'Web3.js',
         'Ethers.js',
         'NFT',
         'Vue.js',
         'Nuxt.js',
         'Options API',
         'Composition API',
         'JavaScript',
         'TypeScript',
         'Buy/Sell',
         'Crypto',
         'Payment API',
         'Trade API',
         'AI',
      ],
      title: `GigaMart`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Web3 marketplace for NFTs and crypto collectibles. Browse, create, buy, sell, and auction NFTs.`,
   },

   {
      company: `Cryplex`,
      link: 'https://cryplex.io',
      image: '/projects/cryplex.png',
      badges: [
         'Web3.js',
         'Ethers.js',
         'Chart.js',
         'D3.js',
         'Vercel',
         'React',
         'Next',
         'SSR',
         'CSR',
         'SSG',
         'SPA',
         'AI',
         'Tailwind',
         'Radix UI',
         'Headless UI',
         'Parsing',
         'Grabbing',
         'Big Data',
      ],
      title: `Cryplex`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Discover, Review, and Rate Top Crypto Projects from all Ecosystems`,
   },

   // 15 - 30

   {
      company: `WINGS Stiftung`,
      link: 'http://wings.ai',
      image: '/projects/wings_stiftung.jpeg',
      badges: ['WEB3', 'Nuxt.js', 'Vue.js', 'React.js', 'Next.js'],
      title: `WINGS Stiftung`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Promotion of new technology developments and applications, in particular, the promotion and maintenance of new open decentralized software architectures, but not exclusively, the promotion of the development of the WINGS protocol and the corresponding technology, as well as the promotion and support of applications using the protocol.`,
   },

   {
      company: `Cryptopay`,
      link: 'https://cryptopay.me/',
      image: '/projects/cryptopay.png',
      badges: ['WEB3', 'Vue.js', 'Nuxt.js', 'HTML5', 'CSS3', 'Tailwind'],
      title: `Cryptopay`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `A simple and secure way to buy and sell cryptocurrency. Get access to 35+ cryptocurrencies and 3 fiat currencies with the Cryptopay App and Visa Card (coming soon!)`,
   },

   {
      company: `Overmind`,
      link: 'https://overmind.xyz/',
      image: '/projects/overmind.png',
      badges: ['WEB3', 'React.js', 'Next.js', 'REST', 'tRPC', 'Tailwind'],
      title: `Overmind`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Learn everything you need to build ground-breaking dApps. Compete to earn rewards and credentials.`,
   },

   {
      company: `T3RN`,
      link: `https://www.t3rn.io`,
      image: '/projects/t3rn.jpeg',
      badges: [
         'WEB3',
         'Wallet',
         'Explorer',
         'React.js',
         'Next.js',
         'HTML5',
         'CSS3',
         'JavaScript',
         'TypeScript',
      ],
      title: `T3RN`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `t3rn offers fast, secure, and cost-efficient swapping, optimizing cross-chain executions by leveraging the modular layers of the t3rn stack for storage, validation, settlement ad consensus.`,
   },

   {
      company: `Hockey Share`,
      link: `https://www.hockeyshare.com`,
      image: '/projects/hockeyshare.jpeg',
      badges: ['HTML', 'CSS', 'JavaScript', 'Canvas', 'Node.js', 'Math'],
      title: `Hockey Share`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Draw Lacrosse Drills on HockeyShare. We are thrilled to introduce our newest feature, Draw Lacrosse Drills on HockeyShare. This feature is designed specifically for coaches and players who want to take their lacrosse game to the next level. With this tool, you can easily create and share custom lacrosse drills with your team or other coaches. The intuitive drawing tools make it easy to diagram plays and break them down before practices or games.`,
   },

   {
      company: `Ledger App Cosmos`,
      link: 'https://ledger-app-cosmos.netlify.app',
      image: '/projects/ledger-app-cosmos.png',
      badges: ['JavaScript', 'TypeScript', 'Cosmos SDK', 'USB SDK', 'C/C++'],
      title: `Ledger App Cosmos`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `1. Connect with Ledger Nano S / X; 2. Unlock your Ledger device; 3. We support version 1.5.4 and higher;`,
   },

   {
      company: `Outset`,
      link: 'https://www.outset.vc',
      image: '/projects/outset.png',
      badges: ['Nuxt.js', 'Vue.js', 'React.js', 'Next.js', 'Python', 'PHP'],
      title: `Outset`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `The automated, real time operating system for SaaS investors and founders.`,
   },

   {
      company: `Minutta`,
      link: 'https://www.minutta.com',
      image: '/projects/minutta.jpg',
      badges: ['Flash', 'Flex', 'ActionScript', 'REST', 'API'],
      title: `Minutta`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Photo greetings mobile and social app.`,
   },

   {
      company: `Orel State University`,
      link: 'https://oreluniver.ru',
      image: '/projects/orel-state-university.png',
      badges: ['HTML', 'CSS', 'PHP', 'JavaScript', 'WordPress'],
      title: `Orel State University`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Orel State University named after I.S. Turgenev is a unique and dynamically developing education-science-production complex in Russia which integrates qualitative education, perspective science and effective production.`,
   },

   {
      company: `Where The Gift`,
      link: ``,
      image: '/projects/where-the-gift.jpeg',
      badges: [
         'HTML',
         'CSS',
         'JavaScript',
         'Canvas',
         'Flash',
         'Flex',
         'ActionScript',
      ],
      title: `Where The Gift`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Where The Gift - Flash/Flex game`,
   },

   {
      company: `Learn Accounting For Free`,
      link: `https://learnaccountingforfree.com`,
      image: '/projects/learn-accounting-for-free.jpeg',
      badges: [
         'HTML',
         'CSS',
         'JavaScript',
         'Canvas',
         'Flash',
         'Flex',
         'ActionScript',
         'PHP',
         'WordPress',
      ],
      title: `Learn Accounting For Free`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Learn Accounting For FREE Produced by the #1 Ranked Accounting University in the World`,
   },

   {
      company: `SideBoss`,
      link: `https://x.com/cappercontests`,
      image: '/projects/sideboss.jpg',
      badges: [
         'HTML',
         'CSS',
         'JavaScript',
         'Canvas',
         'Flash',
         'Flex',
         'ActionScript',
         'PHP',
         'WordPress',
      ],
      title: `SideBoss`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `An Online Platform Where Contestants Compete Against Each Other in Both Season Long and Daily Handicapping Contests.`,
   },

   {
      company: `KwikBio`,
      link: `https://kwikbio.godaddysites.com`,
      image: '/projects/kwikbio.webp',
      badges: [
         'HTML',
         'CSS',
         'JavaScript',
         'Canvas 2d/3d',
         'WebGl',
         'Angular.js',
         'Node.js',
      ],
      title: `KwikBio`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Your gateway to rapid biomedical research.`,
   },

   {
      company: `Life Token`,
      link: `https://www.instagram.com/lifetoken`,
      image: '/projects/lifetoken.jpg',
      badges: [
         'HTML',
         'CSS',
         'JavaScript',
         'Canvas 2d/3d',
         'WebGl',
         'Node.js',
         'Shopify',
      ],
      title: `Life Token Custom Bracelets`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Life Token Custom Bracelets Brand. Spread kindness. Custom jewelry with a meaning. Tag #lifetoken. CUSTOMIZE NOW.`,
   },

   {
      company: `Reservations Center`,
      link: `https://reservationscenter.com`,
      image: '/projects/reservationscenter.png',
      badges: [
         'HTML5',
         'CSS3',
         'JavaScript',
         'TypeScript',
         'React.js',
         'Next.js',
         'Node.js',
      ],
      title: `Reservations Center`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Fast and accurate information, to find the perfect hotel for you. Book your Perfect Hotel.`,
   },

   // 30 - 45

   {
      company: `Planet IRM`,
      link: `https://planetirm.com`,
      image: '/projects/planetirm.webp',
      badges: [
         'HTML5',
         'CSS3',
         'JavaScript',
         'TypeScript',
         'Node.js',
         'Canvas 2D',
         'Canvas 3D',
         '2D/3D',
      ],
      title: `Planet IRM`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Planet IRMAI is Planet Associates next generation SaaS based comprehensive ServiceOps AI-driven Infrastructure Relationship Management Software and Configuration Management Software.`,
   },

   {
      company: `Evango`,
      link: `https://www.evango.net/`,
      image: '/projects/evango.png',
      badges: ['HTML', 'CSS', 'JavaScript', 'TypeScript', 'PHP', 'WordPress'],
      title: `Evango`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `We're about faith and works, prayer and action to bring others home to Christ. Why? Because it works.`,
   },

   {
      company: `Dinner With The Doctor`,
      link: `https://www.dinnerwiththedoctor.com/`,
      image: '/projects/dinnerwiththedoctor.jpg',
      badges: ['HTML', 'CSS', 'JavaScript', 'TypeScript', 'PHP', 'WordPress'],
      title: `Dinner With The Doctor`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Start eating delicious healthy food and improve your health at the same time!`,
   },

   {
      company: `Xymogen`,
      link: `https://www.xymogen.com/`,
      image: '/projects/xymogen.webp',
      badges: ['HTML', 'CSS', 'JavaScript', 'TypeScript', 'PHP', 'WordPress'],
      title: `Xymogen`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Premium Dietary Supplements for Health & Wellness.`,
   },

   {
      company: `Bull Dog Code`,
      link: `https://bulldogcode.com/`,
      image: '/projects/bulldogcode.png',
      badges: ['HTML', 'CSS', 'JavaScript', 'TypeScript', 'PHP', 'WordPress'],
      title: `Bull Dog Code`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `We spend 80% of our time working with Wordpress and 20% integrating it with other great technologies.`,
   },

   // {
   //    company: ``,
   //    link: '',
   //    badges: [''],
   //    title: ``,
   //    logo: undefined,
   //    start: undefined,
   //    end: undefined,
   //    description: ``,
   // },
]
