import { Experience } from '../../types/Experience'

// Responsibilities
// Technologies

export const EXPERIENCES: Experience[] = [
   {
      company: 'CheapHotelsHub.com',
      link: 'https://cheaphotelshub.com',
      badges: ['Office', 'Full-Time'],
      title: 'Chief Technology Officer',
      logo: undefined,
      start: 'Aug 2023',
      end: undefined,
      contents: [
         {
            title: 'Responsibilities',
            description:
               'Technical Leadership (Defining the Technical Strategy and Vision, Architecting the System Infrastructure, Building and Leading a Technical Team, 0 - 1 Product Development (Launching and Maintaining)); Team Leadership; Marketing: Digital Marketing (Google Ads, Meta Ads), Online Marketing (Calls/SMS/MMS/Emails); SEO and SERP; Led 5 Agile teams and managed the entire development process (including personal Kanban backlog strategy); B2B and B2C Data Providers/Vendors, 2D/3Ds Payment Gateways, CI/CD pipelines integrations; Security Compliance & Identity Fundamentals',
         },
         {
            title: 'Technologies',
            description:
               'React.js · Next.js · Node.js · Nest.js · Clerk.js · Vercel · AWS · EC2 · S3 · Go · Rust · UI/UX · Prisma · MongoDB · DynamoDB · MySQL · PostgreSQL · SQLite (C/C++ based) · Tailwind UI · Tailwind CSS · Payment API · Security API · Travel API · Ads API · Anti-fraud API · Anti-scam API · CI/CD · Agile · Scrum · Kanban · Redis · Radix UI · Headless UI · Shadcn UI · Canva · AI · tRPC · gRPC · Zod · Yup · Docker · Kubernetes · Terraform · NPM · PNPM · TURBO',
            items: [
               'React.js',
               'Next.js',
               'Node.js',
               'Nest.js',
               'Clerk.js',
               'Vercel',
               'AWS',
               'EC2',
               'S3',
               'Go',
               'Rust',
               'UI/UX',
               'Prisma',
               'MongoDB',
               'DynamoDB',
               'MySQL',
               'PostgreSQL',
               'SQLite (C/C++ based)',
               'Tailwind UI',
               'Tailwind CSS',
               'Payment API',
               'Security API',
               'Travel API',
               'Ads API',
               'Anti-fraud API',
               'Anti-scam API',
               'CI/CD',
               'Agile',
               'Scrum',
               'Kanban',
               'Redis',
               'Radix UI',
               'Headless UI',
               'Shadcn UI',
               'Canva',
               'AI',
               'tRPC',
               'gRPC',
               'Zod',
               'Yup',
               'Docker',
               'Kubernetes',
               'Terraform',
               'NPM',
               'PNPM',
               'TURBO',
            ],
         },
      ],
   },

   {
      company: 'Super Studios Inc.',
      link: 'https://www.superstudios.io',
      badges: ['Remote', 'Full-Time'],
      title: 'Senior Full Stack Developer',
      logo: undefined,
      start: 'Mar 2023',
      end: undefined,
      contents: [
         {
            title: 'Responsibilities',
            description:
               'Created 3 applications (SSR/CSR/SSG/SPA): Vue.js/Nuxt.js/Pinia/JavaScript/TypeScript responsive HTML5/CSS3 websites; Worked on Web3/Crypto/Blockchain applications (including swaps, trades, wallets for websites); Worked on NFT marketplace, delivered features, worked on fixes/improvements and strengthened security protocols.',
         },
         {
            title: 'Technologies',
            items: [
               'Vue.js',
               'Nuxt.js',
               'Options API',
               'Composition API',
               'Pinia',
               'JavaScript',
               'TypeScript',
               'HTML5',
               'CSS3',
               'Web3',
               'Web3.js',
               'Ethers',
               'Ethers.js',
               'NFT',
               'Crypto',
               'Blockchain',
               'Payment API',
               'Trade API',
               'Wallet',
               'Explorer',
               'AI',
            ],
         },
      ],
   },

   {
      company: 'University of Miami',
      link: 'https://miami.edu',
      badges: ['Remote', 'Full-Time'],
      title: 'Lead Software Engineer',
      logo: undefined,
      start: 'Aug 2022',
      end: 'Mar 2023',
      contents: [
         {
            title: 'Responsibilities',
            description:
               'Led the development and implementation of a cutting-edge software solution for a cancer research project, leveraging advanced technologies and algorithms to analyze and interpret medical data. Designed and implemented data processing pipelines and algorithms to handle large-scale genomic and clinical data sets, facilitating data integration and analysis for cancer research purposes.',
         },
         {
            title: 'Technologies',
            items: [
               'Android',
               'IOS',
               'WebRTC',
               'Video/Audio',
               'SMS/MMS',
               'React.js',
               'Next.js',
               'Nest.js',
               'Node.js',
               'MUI (Material UI)',
               'Tailwind (CSS + UI/UX)',
               'API',
               'RESTful',
               'GraphQL',
               'Figma',
               'MongoDB',
               'DynamoDB',
               'Jira',
               'Trello',
               'SQL',
               'MySQL',
               'JavaScript',
               'TypeScript',
               'NoSQL',
               'Cypress',
               'DevOps',
               'CI/CD',
            ],
         },
      ],
   },

   {
      company: 'Tier1 Financial Solutions',
      link: 'https://www.tier1fin.com',
      badges: ['Remote', 'Full-Time'],
      title: 'Technical Lead',
      logo: undefined,
      start: 'Jan 2022',
      end: 'Aug 2022',
      contents: [
         {
            title: 'Responsibilities',
            description:
               'Led the development of a comprehensive banking and CRM software solution, serving as the Node.js and React full-stack tech lead, responsible for driving the technical direction and ensuring the successful implementation of the system. Architected and designed scalable and robust back-end systems using Node.js, leveraging its event-driven architecture and asynchronous programming model to efficiently handle high-volume transactions and data processing.',
         },
         {
            title: 'Technologies',
            items: [
               'JavaScript',
               'SQL',
               'MySQL',
               'Node.js',
               'React Hooks',
               'RESTful architecture',
               'NoSQL',
               'Storybooks',
               'Next.js',
               'Team Leadership',
               'Microsoft Azure',
               'REST APIs',
               'Vercel',
               'React.js',
               'MongoDB',
               'Leadership',
               'TypeScript',
               'Nest.js',
               'React Context',
            ],
         },
      ],
   },

   {
      company: 'AB InBev',
      link: 'https://www.ab-inbev.com',
      badges: ['Remote', 'Full-Time'],
      title: 'Tech Lead Engineer',
      logo: undefined,
      start: 'Apr 2021',
      end: 'Jan 2022',
      contents: [
         {
            title: 'Responsibilities',
            description:
               'Led the development of a large-scale banking system, serving as the Node.js, Nest.js and React tech lead engineer responsible for architecting and implementing robust and scalable solutions. Optimized banking system performance by implementing caching, indexing, and code optimization with server optimization to efficiently handle high transaction volumes.',
         },
         {
            title: 'Technologies',
            items: [
               'JavaScript',
               'TypeScript',
               'React Native',
               'React Query',
               'React Router',
               'Node.js',
               'CRM Integration',
               'API Integration',
               'REST architecture',
               'CI/CD architecture',
               'React.js',
               'Next.js',
               'Agile',
               'Scrum',
               'Team Leadership',
               'Tech Leadership',
               'CRM Databases',
               'CMS Contents',
               'Azure',
               'Leadership',
               'Banking',
               'Processing',
               'Kafka',
               'RabbitMQ',
               'ActiveMQ',
               'Amazon Web Services (AWS)',
            ],
         },
      ],
   },

   {
      company: 'CiiRUS Vacation Rental Software',
      link: 'https://www.ciirus.com',
      badges: ['Remote', 'Full-Time'],
      title: 'Full Stack Engineer',
      logo: undefined,
      start: 'Jul 2020',
      end: 'Mar 2021',
      contents: [
         {
            title: 'Responsibilities',
            description:
               'Developed and maintained highly scalable and performant full-stack apps for a high-tech enterprise vacation rental platform (B2B and B2C booking engines), utilizing technologies such as Vue, React, Angular for the front end and Node, Go, and Python for the back end. Implemented authentication and authorization systems, secured APIs, and safeguarded data input/output, ensuring robust security and efficient performance.',
         },
         {
            title: 'Technologies',
            items: [
               'JavaScript',
               'AngularJS',
               'Agile Methodologies',
               'Microsoft Azure',
               'TypeScript',
               'HTML5',
               'CSS3',
            ],
         },
      ],
   },

   {
      company: 'Self Employed (US)',
      link: 'https://www.linkedin.com/company/indpendent-contractor',
      badges: ['Remote', 'Full-Time'],
      title: 'Lead Front-end Developer | Lead Back-end Engineer, Team Leader',
      logo: undefined,
      start: 'Mar 2019',
      end: 'Jun 2020',
      contents: [
         {
            title: 'Responsibilities',
            description:
               'Led a team of developers, providing technical guidance, code reviews, and mentoring to ensure the delivery of high-quality code and adherence to best practices. Spearheaded the development of a highly responsive and visually appealing front-end application, utilizing modern frameworks and technologies such as React, Angular, or Vue.',
         },
         {
            title: 'Technologies',
            items: [
               'JavaScript',
               'Node.js',
               'Angular.js',
               'Vue.js',
               'React.js',
               'TypeScript',
               'REST',
               'API',
            ],
         },
      ],
   },

   {
      company: 'Coalition Technologies',
      link: 'https://coalitiontechnologies.com',
      badges: ['Remote', 'Full-Time'],
      title: 'Senior Front-end Developer | Senior Back-end Engineer',
      logo: undefined,
      start: 'Sep 2017',
      end: 'Mar 2019',
      contents: [
         {
            title: 'Responsibilities',
            description:
               'Implement UI/UX interfaces (responsive and adaptive). Optimize performance, scalability, and maintainability of web interfaces. Collaborate with designers and developers for integrated solutions. Implement APIs, databases, and services.',
         },
         {
            title: 'Technologies',
            items: [
               'BigCommerce',
               'Shopify',
               'Wordpress',
               'WooCommerce',
               'Magento 1/2',
               'SEO',
               'SERP',
               'JavaScript',
               'Node.js',
               'Angular.js',
               'Vue.js',
               'React.js',
               'TypeScript',
               'REST',
               'API',
            ],
         },
      ],
   },

   {
      company: 'Cronix MicroSystems',
      link: '',
      badges: ['Office', 'Full-Time'],
      title: 'Chief Technology Officer',
      logo: undefined,
      start: 'Mar 2016',
      end: 'Sep 2017',
      contents: [
         {
            title: 'Responsibilities',
            description:
               'Led the successful implementation of a company-wide digital transformation strategy, modernizing legacy systems and transitioning to a scalable, cloud-native architecture. Mentored and coached software development teams, fostering a culture of continuous learning, innovation, and professional growth.',
         },
         {
            title: 'Technologies',
            items: [
               'Team Leadership',
               'Project Leadership',
               'Product Leadership',
               'Agile',
               'Scrum',
               'Kanban',
               'Software Engineering',
               'System Architecture',
               'API Architecture',
               'UI/UX Architecture',
            ],
         },
      ],
   },

   {
      company: 'Guru.com',
      link: 'https://guru.com',
      badges: ['Remote', 'Full-Time'],
      title: 'Team Lead, Senior Software Developer',
      logo: undefined,
      start: 'Jan 2015',
      end: 'Mar 2016',
      contents: [
         {
            title: 'Responsibilities',
            description:
               'Led and managed a high-performing team of full-stack developers to successfully deliver complex projects using Agile (Scrum) with Kanban. Mentored and coached junior developers, fostering their growth (soft skills) and technical expertise (hard skills). Collaborated with UX/UI designers, automations and manuals QAs. Deliver daily updates and weekly demos.',
         },
         {
            title: 'Technologies',
            items: [
               'JavaScript',
               'TypeScript',
               'Node.js',
               'Express.js',
               'Webpack',
               'Gulp',
               'Grunt',
               'HTML5',
               'CSS3',
               'Git',
               'GitHub',
               'GitLab',
               'Trello',
               'Jira',
               'CI/CD',
               'ES5/ES6',
               'Agile',
               'Scrum',
               'Kanban',
               'Adobe',
               'Figma',
            ],
         },
      ],
   },

   {
      company: 'Scopic Software',
      link: 'https://scopicsoftware.com',
      badges: ['Remote', 'Full-Time'],
      title: 'Senior Web Developer',
      logo: undefined,
      start: 'Feb 2014',
      end: 'Jan 2015',
      contents: [
         {
            title: 'Responsibilities',
            description:
               'Develop interactive web applications (0 - 1 implementation). Work on fixes/improvements/features. Develop rich media applications, work on performance and optimization. Continuous delivery and continuous integration. Using Trello and Jira split tasks between developers and other team members. Provide full reports for PMs and CTOs, handle daily calls and weekly demos.',
         },
         {
            title: 'Technologies',
            items: [
               'JavaScript',
               'Canvas (2D/3D)',
               'HTML5',
               'CSS3',
               'PHP',
               'Laravel',
               'Lumen',
               'Symfony',
               'CodeIgniter',
               'Wordpress',
               'Flash',
               'Flex',
               'MySQL',
               'MsSQL',
               'Linux',
               'Nginx',
               'Apache',
               'Git',
               'GitHub',
               'GitLab',
               'CI/CD',
            ],
         },
      ],
   },
   {
      company: 'Stork',
      link: '',
      badges: ['Office', 'Full-Time'],
      title: 'Full Stack Engineer',
      logo: undefined,
      start: 'Sep 2011',
      end: 'Jan 2014',
      contents: [
         {
            title: 'Responsibilities',
            description:
               'Design and develop web, mobile and social applications (Minutta - 30,000,000 registered users in Eastern Europe). Worked on 3 UI/UX applications 70% of the time: web application (HTML5/CSS3 + Canvas), mobile (Java + Android SDK/NDK) and Flash/Flex. Worked on the high load server 30% of the time: PHP (Laravel + Lumen), MySQL/MsSQL, Linux with Nginx + Apache + Jenkins',
         },
         {
            title: 'Technologies',
            items: [
               'JavaScript',
               'ActionScript',
               'Canvas',
               'HTML5',
               'CSS3',
               'PHP',
               'Flash',
               'Flex',
               'Laravel',
               'Lumen',
               'MySQL',
               'MsSQL',
               'Linux',
               'Nginx',
               'Apache',
               'C/C++',
               'Git',
               'GitHub',
               'GitLab',
               'CI/CD',
               'Server',
               'Jenkins',
               'Java',
            ],
         },
      ],
   },

   {
      company: 'Oryol State Technical University (Oryol STU)',
      link: 'https://int.oreluniver.ru/en',
      badges: ['Office', 'Internship'],
      title: 'Front-end | Back-end: Trainee Developer',
      logo: undefined,
      start: 'Sep 2009',
      end: 'Sep 2011',
      contents: [
         {
            title: 'Responsibilities',
            description:
               'Assist students (1:1 and groups up to 5) in developing responsive (adaptive) web interfaces using HTML, CSS, and JavaScript; API using PHP and PERL; Databases (models and collections) using MySQL and MsSQL. Help students to build Desktop (Linux/Windows) applications using C/C++ and QT3/QT4/QT5. Help in dissertations and graduations writing (mathematics, computer science and physics).',
         },
         {
            title: 'Technologies',
            items: [
               'JavaScript',
               'HTML',
               'CSS',
               'MySQL/MsSQL',
               'Node.js/Express.js',
               'PHP',
               'PERL',
               'C/C++',
               'QT3/QT4/QT5',
            ],
         },
      ],
   },
]
